### ISSUE TITLE
Does not work in ie7

### ISSUE THREAD

**Issue by Zettersten** [mtrpcic/pathjs#12] opened 2011-11-03 20:14 UTC
Documentation shows support for IE7 but the test page does not work.
http://mtrpcic.github.com/pathjs/hashtag_basic.html

**Comment by mtrpcic** [comment] 2011-11-03 20:34
Which version of PathJS are you using?  You can find this by running the command `Path.version` in the JavaScript Console for your browser.

**Comment by Zettersten** [comment] 2011-11-03 22:17
Version 8

**Comment by Zettersten** [comment] 2011-11-03 22:21
0.8 rather

**Comment by mtrpcic** [comment] 2011-11-03 22:35
I'll take a look.  Could you please post the error message as output via the JS Console (Firebug, etc).  Please do not use the minified file for this, as the debug messages become effectively useless once minified.

**Comment by mtrpcic** [comment] 2011-11-03 22:38
I just realized that telling you to output the error message from Firebug makes no sense, since the issue only happens in IE7.  You should be able to see the error message via the IE Developer Tools.  In IE8 they are available by pressing F12, but I'm not sure if it's the same for IE7.

**Comment by Zettersten** [comment] 2011-11-04 02:43
There is no error in the console. It fails silently. If I "listen" after the hash has changed I can get it to work. This causes other issues though.

**Comment by mtrpcic** [comment] 2011-11-04 03:15
I downloaded [IETester](http://www.my-debugbar.com/wiki/IETester/HomePage) to begin testing on multiple IE versions at once.  My example page works properly in IE7 according to this tool, and all tests pass except the "Back Functionality" test, which breaks without `rel` attributes as outline in  [this](http://stackoverflow.com/questions/5382346/ie6-and-ie7-back-forward-hash-tag-navigation-issues) StackOverflow post.  If there is a problem, I need more information than "it fails silently on this particular machine".

**Comment by Zettersten** [comment] 2011-11-04 04:41
Sorry Mike,

I've been busy - I'll try to throw you more details asap. I just wanted 
you to be aware. I'm using IE9's IE7 Mode... I'll get back to you as 
soon as I can.

Thanks for a great util.

Erik

**Comment by mtrpcic** [comment] 2011-11-29 01:58
Has there been any further issues?  Could you provide more feedback?  If I don't hear back within 48 hours I will consider the issues user-fault rather than code-fault, and close this issue.

**Comment by nbeckster** [comment] 2011-12-07 03:29
I can comment to this -- with the ie F12 developer tool (using IE9), set the browser mode to IE7 and the document mode to IE7 standards.  The problem is that a condition like this: ("onhashchange" in window) will return true, but in actuality IE7 does not call this.  As far as how to _really_ see if that's there, and assuming that this behavior is indeed exactly what's being observed, I'd like to offer up a couple solutions.  One is that you just straight up check to see if the browser is IE7, and if so do the polling loop instead.  That has its own problems in using the developer tool because if you put the browser in IE9 mode, but with IE7 document standards... it will look like the browser is IE9, but it's still not gonna call that 'onhashchange' event.  

The second suggestion is that there simply be a little hook there that you can set to force the use of a polling loop.  It's a little surprising to me that no one has seen this behavior in IE7 yet, but maybe I'm just unfortunate in that I have to support it.

**Comment by mtrpcic** [comment] 2011-12-07 04:03
Thanks xyad for giving some helpful information.  I have tested the PathJS library in vanilla IE7 and it appeared to work (perhaps it was in quirks mode?), and it appears that the issues people are having are related to IE7 compatibility mode in IE9.  Is there any way you could test in an actual IE7 installation?  I will attempt to find a Virtual Machine running IE7 tomorrow and test it.

**Comment by nbeckster** [comment] 2011-12-07 04:42
I'll see if I can't do that in the next couple of days.  It'd be nice if this is just a problem with the dev tool not emulating IE7 properly, but a shame too because the tool is awfully convenient for seeing how things are rendered in different versions of IE.

**Comment by mtrpcic** [comment] 2011-12-28 00:45
This has been fixed as of version 0.8.2.  Thank you to @xyad for pointing me in the right direction.  The issue is that IE8 (and likely 9) report that the "onhashchange" event exists even when it "Quirks Mode" or "IE7 Compatibility Mode".  This tells PathJS to use that function, which doesn't actually exist.  I added checks for internet document variables that IE uses to ensure that the right events get fired.

I apologize for the severely delayed response to this issue.  I hope you guys continue to use PathJS and give me feedback whenever you can.

Thanks,

Mike Trpcic

**Closed as completed by mtrpcic** 2011-12-28 00:45 UTC

**Comment by Zettersten** [comment] 2011-12-28 00:52
Thanks Mike!
Thanks Xyad!

Mike Trpcic wrote:
