### ISSUE TITLE
Syntax error, unrecognized expression

### ISSUE THREAD

**Issue by Zettersten** [mtrpcic/pathjs#11] opened 2011-10-28 23:32 UTC
``` javascript
var routes = [
    "#/home",
    "#/obstacles",
    "#/obstacles/:id"
];

Path.map(routes[2]).to(function(){
    app.route(this.path, this.params["id"]);
});
```

When looping through an array of routes, firefox - firebug throws a 
- uncaught exception: Syntax error, unrecognized expression: id

Any reason why this is happening?

**Comment by Zettersten** [comment] 2011-10-28 23:33
in the example above, im obviously not looping... but I am showing when the loop hits the 2nd item which is the item with a param available.

Whenever it hits a route string with a param it throws the error

**Comment by mtrpcic** [comment] 2011-10-28 23:39
Could you provide a complete piece of javascript as a gist and/or pastie with some test routes and I'll take a look immediately.

**Comment by mtrpcic** [comment] 2011-10-28 23:53
I have a suspicion the problem is because you're looping through the routes, and you're attempting to access the parameter "id" in side every run of the loop.  In that situation, the problem would be that some of those routes don't have that parameter.

**Comment by mtrpcic** [comment] 2011-10-28 23:59
I believe the problem may be with your call to `app.route`, where you may potentially be passing in an undefined value in place of `id`.  Please take a look at [this](https://gist.github.com/1323873) gist and run it.  It works in FF and Chrome using the latest PathJS (v0.8).

**Comment by mtrpcic** [comment] 2011-11-29 01:59
Is there any news on your issue?  If there is no word on the issue within 48 hours, I will consider the issue user-fault rather than code-fault and close this issue.

**Comment by mtrpcic** [comment] 2011-12-27 17:31
This issue is closed due to the following two reasons:
- I can not reproduce this bug
- The user who reported it is no longer responding, and as such, I feel it was likely user error

**Closed as completed by mtrpcic** 2011-12-27 17:31 UTC

**Comment by Zettersten** [comment] 2011-12-27 18:30
Sorry Mike, I haven't had time to isolate the issue and fiddle it for you.

If you want to take a look at it, visit nenvy.com/a/css_off

You'll see the error. You can examine the implementation.

I use path.js a ton - so I'm sure I'll eventually get this issue properly documented.

Until then - sorry for the lack of proper "git"!

**Comment by mtrpcic** [comment] 2011-12-27 21:00
I am not getting any errors on the linked page.  What browser were you encountering the errors on?  I'm testing on Firefox 8.0.1.
